### ISSUE TITLE
Missing translation in "Tiempo transcurrido"

### ISSUE THREAD

**Issue by Lucamiz01** [Santi-hr/Acronymate#13]
One of the occurrences of Tiempo transcurrido (the one in the file cmdProgressBar.py line 41) has not been translated. Moreover the translation in the file acronymate.po line 592 should probably be "Elapsed time:" instead of "Time Ellapsed:"

**Comment by Santi-hr** [comment]
Thank you very much for notifying these errors!
It should be fixed right now on the dev branch so they will get into the next release (Which I expect later this summer, as I want to give a try developing the feature requested in #12).
